stages:
  - test

check_and_perftest:
  stage: test
  image: golang:latest
  services:
    - mysql:latest
  variables:
    MYSQL_DATABASE: test
    MYSQL_ROOT_PASSWORD: mysql
  script:
    # - uname -a
    # - go version
    # - go vet $(go list ./...)
    # - go install honnef.co/go/tools/cmd/staticcheck@latest
    # - staticcheck ./...
    # - go test -v $(go list ./...)
    - cd cmd/migration
    - DBUSER=root DBPWD="$MYSQL_ROOT_PASSWORD" go run main.go
    - cd ../service
    - PORT=8080 DBUSER=root DBPWD="$MYSQL_ROOT_PASSWORD" go run main.go &
    - sleep 10
    - cd ../client
    - PORT=8080 go run main.go

# trivy:
#   stage: test
#   image: curlimages/curl:latest
#   script:
#     - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b .
#     - ./trivy fs .

# # jobs run in test stage
# include:
#   - template: Jobs/SAST.gitlab-ci.yml
#   - template: Jobs/Secret-Detection.gitlab-ci.yml