stages:
  - test

check:
  stage: test
  image: golang:latest
  script:
    - go version
    - go vet $(go list ./...)
    - go test -v $(go list ./...)

# test stage
include:
  - template: Jobs/SAST.gitlab-ci.yml
