stages:
  - test

check:
  stage: test
  image: golang:latest
  script:
    - uname -a
    - go version
    - go vet $(go list ./...)
    - apt install staticcheck
    - staticcheck ./...
    - go test -v $(go list ./...)

# trivy:
#   stage: test
#   image: curlimages/curl:latest
#   script:
#     - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b .
#     - ./trivy fs .

# # jobs run in test stage
# include:
#   - template: Jobs/SAST.gitlab-ci.yml
#   - template: Jobs/Secret-Detection.gitlab-ci.yml