image: golang:latest

stages:
  - check
  - test

include:
  - template: Jobs/SAST.gitlab-ci.yml

check:
  stage: check
  script:
    - go version
    - go vet $(go list ./...)
    - go test -v $(go list ./...)
