stages:
  - test

services:
  - mysql:latest

variables:
  MYSQL_DATABASE: test
  MYSQL_ROOT_PASSWORD: mysql

setupdb:
  image: mysql:latest
  script:
  - uname -a
  - apk update
  - apk add go
  - cat scripts/database.sql | mysql -v --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql "$MYSQL_DATABASE"
  - echo "select * from contacts" | mysql -v --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql "$MYSQL_DATABASE"
  - go version


# select:
#   needs: ['setupdb']
#   image: mysql
#   script:
#   - echo "select * from contacts" | mysql -v --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql "$MYSQL_DATABASE"

# perftest:
#   needs: ['setupdb']
#   stage: test
#   image: golang:latest
#   script:
#     - uname -a
#     - go version
#     - cd cmd/service
#     - PORT=8080 DBUSER=root DBPWD="$MYSQL_ROOT_PASSWORD" go run main.go

# check:
#   stage: test
#   image: golang:latest
#   script:
#     - uname -a
#     - go version
#     - go vet $(go list ./...)
#     - go install honnef.co/go/tools/cmd/staticcheck@latest
#     - staticcheck ./...
#     - go test -v $(go list ./...)

# trivy:
#   stage: test
#   image: curlimages/curl:latest
#   script:
#     - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b .
#     - ./trivy fs .

# # jobs run in test stage
# include:
#   - template: Jobs/SAST.gitlab-ci.yml
#   - template: Jobs/Secret-Detection.gitlab-ci.yml