stages:
  - test

golang_tests:
  stage: test
  image: golang:latest
  services:
    - mysql:latest
  variables:
    MYSQL_DATABASE: test
    MYSQL_ROOT_PASSWORD: mysql
  script:
    - uname -a
    - go version
    - go vet $(go list ./...)
    - go install honnef.co/go/tools/cmd/staticcheck@latest
    - staticcheck ./...
    - go test -v $(go list ./... | grep -v integrationtest)
    - cd cmd/migration
    - DBHOST=mysql DBUSER=root DBPWD="$MYSQL_ROOT_PASSWORD" go run main.go -file=../../scripts/database.sql
    - cd ../..
    - DBHOST=mysql DBUSER=root DBPWD="$MYSQL_ROOT_PASSWORD" go test -v ./internal/integrationtest ./internal/service/

trivy:
  stage: test
  image: curlimages/curl:latest
  script:
    - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b .
    - ./trivy fs .

# jobs run in test stage
include:
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml
