image: golang:latest

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
  cache:
    paths:
      - .go/pkg/mod/

stages:
  - check
#test
check:
  stage: check
  extends: .go-cache
  script:
    - go vet
    - go test -v